/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BarChart: typeof import('./src/components/BarChart.vue')['default']
    BaseModal: typeof import('./src/components/BaseModal.vue')['default']
    ChartsSection: typeof import('./src/components/ChartsSection.vue')['default']
    DashboardSidebar: typeof import('./src/components/DashboardSidebar.vue')['default']
    ExportSection: typeof import('./src/components/ExportSection.vue')['default']
    MetricCard: typeof import('./src/components/MetricCard.vue')['default']
    MetricsGrid: typeof import('./src/components/MetricsGrid.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sidebar: typeof import('./src/components/Sidebar.vue')['default']
    StudentRegisterModal: typeof import('./src/components/StudentRegisterModal.vue')['default']
  }
}
